SELECT * FROM employee_table ORDER BY NAME;
SELECT * FROM employee_table ORDER BY COUNTRY DESC;
SELECT * FROM employee_table ORDER BY COUNTRY DESC, AGE ASC;
SELECT COUNTRY, COUNT(*) FROM employee_table GROUP BY COUNTRY; 
SELECT COUNTRY, COUNT(*) FROM employee_table GROUP BY COUNTRY HAVING COUNT(*)>1;
SELECT COUNTRY, MAX(AGE) FROM employee_table GROUP BY COUNTRY HAVING MAX(AGE)<50 ORDER BY COUNTRY DESC;
SELECT COUNTRY, MAX(AGE) FROM employee_table GROUP BY COUNTRY HAVING MAX(AGE)<50 ORDER BY COUNTRY DESC LIMIT 2;



