SELECT * FROM employee_table ORDER BY NAME;
SELECT * FROM employee_table ORDER BY COUNTRY DESC;
SELECT * FROM employee_table ORDER BY COUNTRY DESC, AGE ASC;
SELECT COUNTRY, COUNT(*) FROM employee_table GROUP BY COUNTRY;  
